{
 "title": "4 Golden Sinals",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color:DarkOrange;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-code\"></i> Visão Geral - 4 Golden Signals <i class=\"fa fa-code\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Metrics Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<h1 style=\"background-color:Gold;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-clock-o\"></i> Latency <i class=\"fa fa-clock-o\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"}) by(uri, method)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$application\", status=~\"2.*\", uri!~\".actuator.*\"}) / sum by(uri, method) (http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$application\", outcome=~\"SERVER_ERROR|CLIENT_ERROR\"})"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri, method)(http_server_requests_seconds_sum{application=\"$application\", uri!~\".actuator.*\"}) / sum by(uri, method)(http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Status Code HTTP Request",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"200\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"200\"}[$__range])) / 100)",
     "legendFormat": "200"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"201\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"201\"}[$__range])) / 100)",
     "legendFormat": "201"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"202\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"202\"}[$__range])) / 100)",
     "legendFormat": "202"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"204\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"204\"}[$__range])) / 100)",
     "legendFormat": "204"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"400\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"400\"}[$__range])) / 100)",
     "legendFormat": "400"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"401\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"401\"}[$__range])) / 100)",
     "legendFormat": "401"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"403\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"403\"}[$__range])) / 100)",
     "legendFormat": "403"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"409\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"409\"}[$__range])) / 100)",
     "legendFormat": "409"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"408\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"408\"}[$__range])) / 100)",
     "legendFormat": "408"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"404\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"404\"}[$__range])) / 100)",
     "legendFormat": "404"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"500\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"500\"}[$__range])) / 100)",
     "legendFormat": "500"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"502\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"502\"}[$__range])) / 100)",
     "legendFormat": "502"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"503\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"503\"}[$__range])) / 100)",
     "legendFormat": "503"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"504\"}[$__range])) - (5 * sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", status=\"504\"}[$__range])) / 100)",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri, method) (http_server_requests_seconds_count{application=\"$application\", status=~\"5.*\", uri!~\".actuator.*\"}) / sum by(uri, method) (http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"})",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "PR 90 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.90,sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".actuator.*\"}[1m])) by(uri, method, le))",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".actuator.*\"}[1m])) by(uri, method, le))",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_requests_seconds_bucket{application=\"$application\", uri!~\".actuator.*\"}[1m])) by(uri, method, le))",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri, method)(rate(http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"}[1m]))",
     "legendFormat": "{{method}}{{uri}}"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max (max_over_time(http_server_requests_seconds_max{application=\"$application\", uri!~\".actuator.*\"}[$__range])) by(uri, outcome, method))"
    },
    {
     "expr": "sum (increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"}[$__range])) by(uri, outcome, method)"
    },
    {
     "expr": "sum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_sum{application=\"$application\", uri!~\".actuator.*\"}[$__range])\n)\n/ \nsum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".actuator.*\"}[$__range])\n)"
    }
   ]
  },
  { "title": "Metrics Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<h1 style=\"background-color:DodgerBlue;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-exchange\"></i> Traffic <i class=\"fa fa-exchange\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Metrics Erros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "<h1 style=\"background-color:DarkRed;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-exclamation-triangle\"></i> Error <i class=\"fa fa-exclamation-triangle\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Exceptions",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(exception) (increase(http_server_requests_seconds_count{exception!=\"none\", application=\"$application\"}[$__range]))) > 0"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (method, uri, exception, status) (\n        increase(\n            http_server_requests_seconds_count{application=\"$application\", status=~\"5..|400|404|499\"}[$__range]\n        )\n    ) > 0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)"
    }
   ]
  },
  { "title": "Metrics Saturation ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "<h1 style=\"background-color:DarkGreen;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-thermometer-three-quarters\"></i> Saturation <i class=\"fa fa-thermometer-three-quarters\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{application=\"api-cadastro-pessoas\",instance=\"host.docker.internal:8080\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 },
   "options": {
    "content": "<h1 style=\"background-color:#B5485D;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-building-o\"></i> Visão Geral - Metricas de negócio <i class=\"fa fa-building-o\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Person Register Flow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "<h1 style=\"background-color:#900C3F;\">\r\n   <center>\r\n      <b>\r\n      <font size=\"6\" color=\"#181b1f\" >\r\n      <i class=\"fa fa-play\"></i> Person Register Flow <i class=\"fa fa-play\"></i>\r\n      </font>\r\n      <b/>\r\n   </center>\r\n</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Person Register Flow",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "person_service_save_total{application=\"$application\"}",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}