server:
  address: localhost
  port: 8081
  ssl:
    enabled: false
springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: desc
    disable-swagger-default-url: true
  packages-to-scan:
    - io.github.wesleyosantos91.api
spring:
  application:
    name: api-cadastro-pessoas
  datasource:
    url: ${DATABASE_HOST:jdbc:mysql://localhost:3306/dev?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 60000
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/ddl,classpath:db/dml
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      http.server.requests: true
      person.service.save: true
      person.service.search: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        person.service.save: true
        person.service.search: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.98, 0.99
        person.service.save: 0.5, 0.75, 0.95, 0.98, 0.99
        person.service.search: 0.5, 0.75, 0.95, 0.98, 0.99
      slo:
        http.server.request: 500ms
        person.service.save: 500ms
        person.service.search: 500ms
